AllCops:
  TargetRubyVersion: 2.1
  Exclude:
    - gemfiles/**/*

Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - npmdc.gemspec

# FIXME:

Metrics/LineLength:
  Exclude:
    - lib/npmdc/checker.rb
    - lib/npmdc/modules_directory.rb

Metrics/MethodLength:
  Exclude:
    - lib/npmdc/checker.rb
